### ndarray 연산

##### 기본 연산

In [2]:
import numpy as np

In [5]:
arr_a = np.arange(1, 10).reshape(3, 3)
arr_b = np.full_like(arr_a, 3)
print(arr_a)
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [6]:
# 덧셈
print(arr_a + arr_b)
print(np.add(arr_a, arr_b))

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
# 뺄셈
print(arr_a - arr_b)
print(np.subtract(arr_a, arr_b))

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [14]:
# 곱셈
print(arr_a * arr_b)
print(np.multiply(arr_a, arr_b))

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [15]:
# 나눗셈
print(arr_a / arr_b)
print(np.divide(arr_a, arr_b))

[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [ ]:
# 특수 연산 1: 거듭제곱
print(arr_a ** arr_b)
print(np.power(arr_a, arr_b))
print(np.square(arr_a))     # 제곱   

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
# 특수 연산 2: 몫 
print(arr_a // arr_b)
print(np.floor_divide(arr_a, arr_b))

[[0 0 1]
 [1 1 2]
 [2 2 3]]


In [ ]:
# 특수 연산 3: 나머지
print(arr_a % arr_b)
print(np.mod(arr_a, arr_b))

[[1 2 0]
 [1 2 0]
 [1 2 0]]
[[1 2 0]
 [1 2 0]
 [1 2 0]]


In [19]:
# 제곱근
print(np.sqrt(arr_a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


---

##### broadcasting 연산
- 두 배열의 shape이 다르면 broadcasting 연산을 수행한다.
- shape이 작은 쪽이 큰 쪽에 맞춰 확장한다.
- 두 배열의 행 또는 열이 일치해야 확장 가능하다.
- 크기가 1인 경우 무조건 확장 가능하다.
- shape이 다른 경우 마지막 축부터 차원이 동일한지 비교한다.

In [ ]:
# arr_a = np.arange(1, 10).reshape(3, 3)

result_arr = arr_a * np.array([[5, 5, 5], [5, 5, 5], [5, 5, 5]]) # (3, 3)
result_arr = arr_a * np.array([5, 5, 5]) # (3,)
result_arr = arr_a * np.array([5]) # (1,)
result_arr = arr_a * 5 # 스칼라값
result_arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([5, 10, 15]) # (3,)
arr1 + arr2

array([[ 6, 12, 18],
       [ 9, 15, 21]])

In [31]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([[100], [200]]) # (2, 1)
arr1 + arr2

array([[101, 102, 103],
       [204, 205, 206]])

In [ ]:
arr1 = np.array([1, 2, 3]) # (3,)
arr2 = np.array([[4], [5], [6]]) # (3, 1)
arr1.shape, arr2.shape
arr1 + arr2

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
arr1 = np.array([[1, 2, 3], [1, 2, 3]]) # (2, 3)
arr2 = np.array([1, 2]) # (2,)
# arr1 + arr2 # ValueError

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

---

##### 행렬 곱셈
- 점곱연산 (Dot Product / 내적)
    - 두 행렬 A, B의 곱셈은 첫 번째 행렬 A의 행과 두 번째 행렬 B의 열 간의 곱셈을 수행한다.
    - 첫 번째 행렬 A의 열의 수와 두 번째 행렬 B의 행의 수가 같아야 한다.
    - 연산 결과의 shape은 (첫 번째 행렬 A의 행수, 두 번째 행렬 B의 열수) 이다.

In [36]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
print(arr1 * arr2)
print(arr1.shape, arr2.shape, (arr1*arr2).shape)

print(np.dot(arr1, arr2))
print(np.dot(arr1, arr2).shape)

[[ 5 12]
 [21 32]]
(2, 2) (2, 2) (2, 2)
[[19 22]
 [43 50]]
(2, 2)


In [ ]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8], [9, 10], [11, 12]])
print(arr3.shape, arr4.shape, np.dot(arr3, arr4).shape)
# np.dot(arr3, arr4) -> (2, 3) * (3, 2) = (2, 2)
# np.dot(arr3, arr4) -> (3, 2) * (2, 3) = (3, 3)

(2, 3) (3, 2) (2, 2)


In [ ]:
# Quiz! shape으로만 결과 판단하기

# (100, 20000) (20000, 100) : (100, 100)
# (20000, 100) (100, 20000) : (20000, 20000)
# (100, 20000) (100, 20000) : 내적 안됨

IndentationError: unexpected indent (2958458924.py, line 3)

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)

# @
# print(arr @ arr) # (2, 3) (2, 3)

# .T
print(arr)
print(arr.T) # arr.T = arr의 전치행렬 (행-열을 교환) 
print(arr @ arr.T) 

# matmul()
print(np.matmul(arr, arr.T))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


---

##### 연산 함수 및 집계 함수

In [44]:
arr_negative = np.array([[-1, -2], [-100, -200]])
arr_float = np.array([[1.234, 5.678], [7.89, 10.123]])
arr = np.arange(1, 7).reshape(2, 3)

In [45]:
# 절대값
np.abs(arr_negative)

array([[  1,   2],
       [100, 200]])

In [ ]:
# 올림/반올림

print(np.ceil(arr_float))
print(np.round(arr_float))
print(np.round(arr_float, 2))

[[ 2.  6.]
 [ 8. 11.]]
[[ 1.  6.]
 [ 8. 10.]]
[[ 1.23  5.68]
 [ 7.89 10.12]]


In [ ]:
arr_float = np.array([[1.234, -5.678], [-7.89, 10.123]])

# 내림 (지정된 수보다 작은 최대 정수)
print(np.floor(arr_float))

# 버림 (절삭)
print(np.trunc(arr_float))

[[ 1. -6.]
 [-8. 10.]]
[[ 1. -5.]
 [-7. 10.]]


In [ ]:
# 최대값/최소값
print(arr) # arr = np.arange(1, 7).reshape(2, 3)

print(np.max(arr))
print(np.min(arr))

print(np.max(arr, axis=0)) # 행 기준 (행을 고정하고, 같은 열에서 가장 큰 값)
print(np.min(arr, axis=1)) # 열 기준 (열을 고정하고, 같은 행에서 가장 작은 값)

[[1 2 3]
 [4 5 6]]
6
1
[4 5 6]
[1 4]
