### ndarray 정렬

In [1]:
import numpy as np

##### 1차원 배열 정렬

In [31]:
arr = np.random.randint(1, 11, 10)
arr

array([6, 2, 1, 1, 1, 3, 3, 4, 7, 7], dtype=int32)

In [ ]:
# np.sort(arr) : 정렬된 ndarry를 반환

np.sort(arr)
print(arr)


array([1, 1, 1, 2, 3, 3, 4, 6, 7, 7], dtype=int32)

In [33]:
np.sort(arr)[::-1]

array([7, 7, 6, 4, 3, 3, 2, 1, 1, 1], dtype=int32)

---

##### 2차원 배열 정렬

In [53]:
arr = np.random.randint(10, size=(3, 4))    # 0 이상 10 미만
arr

array([[2, 9, 0, 2],
       [1, 5, 9, 5],
       [9, 5, 5, 9]], dtype=int32)

In [ ]:
np.sort(arr)    # 기본값 axis=1

array([[0, 2, 2, 9],
       [1, 5, 5, 9],
       [5, 5, 9, 9]], dtype=int32)

In [ ]:
print(np.sort(arr, axis=0)) # 행 방향 정렬 (같은 열 안에서 정렬)
print(np.sort(arr, axis=1)) # 열 방향 정렬 (같은 행 안에서 정렬)

[[1 5 0 2]
 [2 5 5 5]
 [9 9 9 9]]
[[0 2 2 9]
 [1 5 5 9]
 [5 5 9 9]]


In [ ]:
print(np.sort(arr, axis=None))  # axis=None 축 무시 (행/열 구분없이 모든 값 정렬)
print(np.sort(arr, axis=None).shape)

[0 1 2 2 5 5 5 5 9 9 9 9]
(12,)


##### np.argsort
- 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
- 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
- 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환

In [59]:
arr = np.array([100, 400, 200, 300])
print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]
