# 출력층 설계 (Output layer)

In [1]:
!pip3 install torch torchvision torchaudio

   ---------------------------------------- 0.0/204.1 MB ? eta -:--:--
   ---------------------------------------- 1.8/204.1 MB 11.2 MB/s eta 0:00:19
    --------------------------------------- 3.1/204.1 MB 10.8 MB/s eta 0:00:19
   - -------------------------------------- 5.2/204.1 MB 9.1 MB/s eta 0:00:22
   - -------------------------------------- 8.1/204.1 MB 10.3 MB/s eta 0:00:20
   -- ------------------------------------- 11.8/204.1 MB 11.9 MB/s eta 0:00:17
   -- ------------------------------------- 14.9/204.1 MB 12.5 MB/s eta 0:00:16
   --- ------------------------------------ 18.1/204.1 MB 13.4 MB/s eta 0:00:14
   --- ------------------------------------ 19.1/204.1 MB 12.5 MB/s eta 0:00:15
   ---- ----------------------------------- 21.8/204.1 MB 12.0 MB/s eta 0:00:16
   ---- ----------------------------------- 24.1/204.1 MB 12.3 MB/s eta 0:00:15
   ----- ---------------------------------- 26.5/204.1 MB 12.0 MB/s eta 0:00:15
   ----- ---------------------------------- 29.1/204.1

### 소프트맥스 오버플로우 방지

In [3]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

def stable_softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)


x = np.array([1000, 1001, 1002])

print(softmax(x))
print(stable_softmax(x))

[nan nan nan]
[0.09003057 0.24472847 0.66524096]


C:\Users\Playdata\AppData\Local\Temp\ipykernel_14444\3860681584.py:4: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
C:\Users\Playdata\AppData\Local\Temp\ipykernel_14444\3860681584.py:5: RuntimeWarning: invalid value encountered in divide
  return exp_x / np.sum(exp_x)


- PyTorch 라이브러리 함수 사용

In [11]:
import torch
import torch.nn.functional as F

x = torch.tensor([1000, 1001, 1002], dtype=torch.float32)

softmax_output = F.softmax(x, dim=0)    # dim: softmax를 적용할 축
print(softmax_output)

sigmoid_output = torch.sigmoid(x)
print(sigmoid_output)

tensor([0.0900, 0.2447, 0.6652])
tensor([1., 1., 1.])


### 손실 함수와 연계

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# 간단한 다중 클래스 분류 모델 정의 (입력 값: 5개, 출력: 3 클래스)
class SimpleMultiClassModel(nn.Module):
    def __init__(self):
        super(SimpleMultiClassModel, self).__init__()
        self.fc = nn.Linear(5, 3)

    def forward(self, x):
        return self.fc(x)
    
model = SimpleMultiClassModel()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# 데이터 생성
inputs = torch.randn(4, 5)
labels = torch.tensor([0, 2, 1, 0])

for _ in range(10):
    preds = model(inputs)           # 순전파
    loss = criterion(preds, labels) # 손실 계산
    print(loss.item())

    optimizer.zero_grad()   # 이전 단계에서 계산된 기울기를 0으로 초기화
    loss.backward()         # 손실에 대한 역전파 수행 (파라미터에 대한 기울기 계산)
    optimizer.step()        # 계산된 기울기를 사용하여 옵티마이저가 모델의 파라미터 업데이트

1.3633761405944824
1.1169312000274658
0.9259476661682129
0.7737959623336792
0.6520293354988098
0.5545705556869507
0.47627758979797363
0.41363489627838135
0.36415624618530273
0.32536399364471436
